layout_spectrum: 0.33264742582492385
typography_spectrum: 0.940252377924205
color:
  lightness: 0.4004130763873126
  brandColors:
    - '#040404'
    - '#F5F5F5'
    - '#B8B8B8'
    - '#282828'
    - '#4E4E4E'
  saturation: 0.9328303775240179
  brandStrength: 0.9414070773930611
  rhythmicContrast: 0.25024603246157934
coverPrefs:
  filter: false
name: Pale Ape
analytics: {}
purpose:
  - url: 'mailto:booking@paleape.com'
    type: contact
    label: Book the Ape
description: Some call it music...
author:
  name: Brian Wickliff
  email: brian@hicksmokey.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/7d249d61-759a-4190-b2c2-5e8a0642898f.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/7d249d61-759a-4190-b2c2-5e8a0642898f.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
navigation:
  - name: Upcoming Shows
    url: 'http://bandsintown.com/PaleApe?came_from=234'
    type: external
  - name: Soundcloud
    url: 'https://soundcloud.com/paleape/albums'
    type: external
  - name: Bandcamp
    url: 'https://paleape.bandcamp.com'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/paleape/'
    type: external
  - name: Twitter
    url: 'https://twitter.com/PaleApeBand'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/paleape/'
    type: external
favicon: null
content_rating:
  adult: false
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f4f95b4f-ce6e-4f7c-97cf-5cd3f650ea96.jpg
title: Pale Ape
opengraph: {}
url: 'https://paleape.com'
github: true
