typography_spectrum: 0.4306224712636322
color:
  brandStrength: 0.0833922172896564
  lightness: 0.6272312426008284
  saturation: 0.9398733305279166
  rhythmicContrast: 0.9405249371193349
  brandColors:
    - '#040404'
    - '#F5F5F5'
    - '#B8B8B8'
    - '#282828'
    - '#4E4E4E'
layout_spectrum: 0.1297578124795109
author:
  name: Brian Wickliff
  email: brian@hicksmokey.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/92de09d8-5ddd-4244-b896-0ccff935a150.jpg
name: Pale Ape
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9742e9c6-76fc-425e-a305-c55b3ba64e6d.ico
title: Some Call It Music...
description: Some call it music...
